module.exports = [
  { name: "Ahinsa", url: "/marca/ahinsa/" },
  { name: "Altra", url: "/marca/altra/" },
  { name: "Angles Fashion", url: "/marca/angles-fashion/" },
  { name: "Asgard", url: "/marca/asgard/" },
  { name: "Baer", url: "/marca/baer/" },
  { name: "Bahe", url: "/marca/bahe/" },
  { name: "Barebarics", url: "/marca/barebarics/" },
  { name: "Barebound", url: "/marca/barebound/" },
  { name: "Barefoot Pals", url: "/marca/barefoot-pals/" },
  { name: "Bearfoot", url: "/marca/bearfoot/" },
  { name: "Bedrock", url: "/marca/bedrock/" },
  { name: "Belenka", url: "/marca/belenka/" },
  { name: "Birchbury", url: "/marca/birchbury/" },
  { name: "Birkenstock", url: "/marca/birkenstock/" },
  { name: "Bobux", url: "/marca/bobux/" },
  { name: "Bohempia", url: "/marca/bohempia/" },
  { name: "Botky Mechovky", url: "/marca/botky-mechovky/" },
  { name: "Butterfly Your World", url: "/marca/butterfly-your-world/" },
  { name: "Camper", url: "/marca/camper/" },
  { name: "Carets", url: "/marca/carets/" },
  { name: "Chala", url: "/marca/chala/" },
  { name: "Cinderollies", url: "/marca/cinderollies/" },
  { name: "Clotsy", url: "/marca/clotsy/" },
  { name: "Correct Toes", url: "/marca/correct-toes/" },
  { name: "Crupon", url: "/marca/crupon/" },
  { name: "Davinci Footwear", url: "/marca/davinci-footwear/" },
  { name: "Deliberate Life Adventure", url: "/marca/deliberate-life-adventure/" },
  { name: "Dextra Perspective", url: "/marca/dextra-perspective/" },
  { name: "Dolfie Paradise", url: "/marca/dolfie-paradise/" },
  { name: "Duchess Fox", url: "/marca/duchess-fox/" },
  { name: "Earth Runners", url: "/marca/earth-runners/" },
  { name: "Earthing Moccasins", url: "/marca/earthing-moccasins/" },
  { name: "Etsy", url: "/marca/etsy/" },
  { name: "Everleigh Meadow", url: "/marca/everleigh-meadow/" },
  { name: "Faemoon Wolf Designs", url: "/marca/faemoon-wolf-designs/" },
  { name: "Feelbarefoot", url: "/marca/feelbarefoot/" },
  { name: "Feelgrounds", url: "/marca/feelgrounds/" },
  { name: "Fleeters", url: "/marca/fleeters/" },
  { name: "Flux Footwear", url: "/marca/flux-footwear/" },
  { name: "Freet", url: "/marca/freet/" },
  { name: "Gaucho Ninja", url: "/marca/gaucho-ninja/" },
  { name: "Gea Soles", url: "/marca/gea-soles/" },
  { name: "Grecian", url: "/marca/grecian/" },
  { name: "Groundies", url: "/marca/groundies/" },
  { name: "High Feels", url: "/marca/high-feels/" },
  { name: "Hoss Handmade", url: "/marca/hoss-handmade/" },
  { name: "Icarus", url: "/marca/icarus/" },
  { name: "Injinji", url: "/marca/injinji/" },
  { name: "Jack And Lily", url: "/marca/jack-and-lily/" },
  { name: "Jan Jul", url: "/marca/jan-jul/" },
  { name: "Jenon Leather", url: "/marca/jenon-leather/" },
  { name: "Joe Nimble", url: "/marca/joe-nimble/" },
  { name: "Juuri", url: "/marca/juuri/" },
  { name: "Kingdom Of Wow", url: "/marca/kingdom-of-wow/" },
  { name: "Koel", url: "/marca/koel/" },
  { name: "Lang S", url: "/marca/lang-s/" },
  { name: "Lems", url: "/marca/lems/" },
  { name: "Libertas", url: "/marca/libertas/" },
  { name: "Lisbeth Joe", url: "/marca/lisbeth-joe/" },
  { name: "Little Love Bug", url: "/marca/little-love-bug/" },
  { name: "Lonnies", url: "/marca/lonnies/" },
  { name: "Lono Wear", url: "/marca/lono-wear/" },
  { name: "Luks", url: "/marca/luks/" },
  { name: "Luna", url: "/marca/luna/" },
  { name: "Magical", url: "/marca/magical/" },
  { name: "Manitoba", url: "/marca/manitoba/" },
  { name: "Merrell", url: "/marca/merrell/" },
  { name: "Minnetonka", url: "/marca/minnetonka/" },
  { name: "Mukishoes", url: "/marca/mukishoes/" },
  { name: "Naboso", url: "/marca/naboso/" },
  { name: "Nons", url: "/marca/nons/" },
  { name: "Northsole", url: "/marca/northsole/" },
  { name: "Notace", url: "/marca/notace/" },
  { name: "Notorious Lift", url: "/marca/notorious-lift/" },
  { name: "Oesh", url: "/marca/oesh/" },
  { name: "Ohne Project", url: "/marca/ohne-project/" },
  { name: "Origo", url: "/marca/origo/" },
  { name: "Paisley", url: "/marca/paisley/" },
  { name: "Paperkrane", url: "/marca/paperkrane/" },
  { name: "Peerko", url: "/marca/peerko/" },
  { name: "Peluva", url: "/marca/peluva/" },
  { name: "Peracles", url: "/marca/peracles/" },
  { name: "Plae", url: "/marca/plae/" },
  { name: "Posh Panda", url: "/marca/posh-panda/" },
  { name: "Prime Trotter", url: "/marca/prime-trotter/" },
  { name: "Realfoot", url: "/marca/realfoot/" },
  { name: "Ruby Workshop", url: "/marca/ruby-workshop/" },
  { name: "Running Pads", url: "/marca/running-pads/" },
  { name: "Rutsu", url: "/marca/rutsu/" },
  { name: "Saguaro Barefoot", url: "/marca/saguaro-barefoot/" },
  { name: "Savopoulos", url: "/marca/savopoulos/" },
  { name: "Shamma", url: "/marca/shamma/" },
  { name: "Shapen", url: "/marca/shapen/" },
  { name: "Softstar", url: "/marca/softstar/" },
  { name: "Sole Runner", url: "/marca/sole-runner/" },
  { name: "Splay", url: "/marca/splay/" },
  { name: "Steger", url: "/marca/steger/" },
  { name: "Strong Feet Athletics", url: "/marca/strong-feet-athletics/" },
  { name: "Sullivent", url: "/marca/sullivent/" },
  { name: "Tadeevo", url: "/marca/tadeevo/" },
  { name: "Ten Little", url: "/marca/ten-little/" },
  { name: "The Drifter Leather", url: "/marca/the-drifter-leather/" },
  { name: "The Storehouse Flats", url: "/marca/the-storehouse-flats/" },
  { name: "Tikki", url: "/marca/tikki/" },
  { name: "Tip Toey Joey", url: "/marca/tip-toey-joey/" },
  { name: "Toetem", url: "/marca/toetem/" },
  { name: "Tolos", url: "/marca/tolos/" },
  { name: "Tomar Creations", url: "/marca/tomar-creations/" },
  { name: "True Linkswear", url: "/marca/true-linkswear/" },
  { name: "Tyr", url: "/marca/tyr/" },
  { name: "Unshoes Footwear", url: "/marca/unshoes-footwear/" },
  { name: "Vega Barefoot", url: "/marca/vega-barefoot/" },
  { name: "Verloop", url: "/marca/verloop/" },
  { name: "Vibram", url: "/marca/vibram/" },
  { name: "Vivobarefoot", url: "/marca/vivobarefoot/" },
  { name: "Whitin", url: "/marca/whitin/" },
  { name: "Wildling", url: "/marca/wildling/" },
  { name: "Xero", url: "/marca/xero/" },
  { name: "Yosi Samra", url: "/marca/yosi-samra/" },
  { name: "Zaqq", url: "/marca/zaqq/" },
  { name: "Zara", url: "/marca/zara/" },
  { name: "Zeazoo", url: "/marca/zeazoo/" },
  { name: "Zkama", url: "/marca/zkama/" },
  { name: "Zlatush", url: "/marca/zlatush/" },
  { name: "Zuna", url: "/marca/zuna/" },
  { name: "Zuzii Footwear", url: "/marca/zuzii-footwear/" },
];
